variables:
  BUILDER_IMAGE: 560755210414.dkr.ecr.eu-central-1.amazonaws.com/devops/processing-java-builder:j17.0.8-p555767
  GRADLE_USER_HOME: .gradle-home

  ARTIFACT_COMPRESSION_LEVEL: fastest
  CACHE_COMPRESSION_LEVEL: slowest
  FF_USE_FASTZIP: 'true'
  TRANSFER_METER_FREQUENCY: 2s

stages:
  - cache-build
  - source-build

populate-gradle-cache:
  cache:
    - key: gradle
      policy: pull-push
      paths:
        - $GRADLE_USER_HOME/caches/jars-9
        - $GRADLE_USER_HOME/caches/modules-2
        - $GRADLE_USER_HOME/caches/transforms-3
        - $GRADLE_USER_HOME/notifications
        - $GRADLE_USER_HOME/wrapper
        - spring-boot-admin/.frontend-gradle-plugin
        - spring-boot-admin/node
        - spring-boot-admin/node_modules
  image: $BUILDER_IMAGE
  only:
    refs:
      - master
      - vivid
    changes:
      - '*/build.gradle.kts'
      - '*/settings.gradle.kts'
      - build-logic/**/*
      - gradle/libs.versions.toml
      - gradle/wrapper/gradle-wrapper.properties
      - settings.gradle.kts
      - spring-boot-admin/package-lock.json
      - spring-boot-admin/package.json
  script:
    - env | sort
    - echo https://nexus.px019.net/repository/registry.npmjs.org/_auth=$NEXUS_USER:$(echo $NEXUS_PASS | base64) >> ~/.npmrc
    - ./gradlew clean dependencies installNode installFrontend --parallel
  stage: cache-build
  tags: [ build ]

gradle-build:
  artifacts:
    when: always
    paths:
      - build/reports
      - '*/build/reports'
  cache:
    - key: gradle
      policy: pull
      paths:
        - $GRADLE_USER_HOME
    - key: build-$CI_COMMIT_REF_NAME
      policy: pull-push
      paths:
        - $GRADLE_USER_HOME/caches/build-cache-1
        - '*/build'
        - build
  image: $BUILDER_IMAGE
  script:
    - env | sort
    - echo registry=https://nexus.px019.net/repository/registry.npmjs.org > ~/.npmrc
    - ./gradlew build assembleFrontend publish version --parallel -Dorg.gradle.jvmargs=-Xmx2g
  stage: source-build
  tags: [ build ]
